version: '3.8'

networks:
  network_swarm_public:
    external: true

services:
  api:
    image: ghcr.io/Fagner3g/houseapp-api:${TAG:-latest}
    env_file:
      - /opt/env/houseapp/api.env
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.houseapp-api.rule=Host(`api.jarvis.dev.br`)
        - traefik.http.routers.houseapp-api.entrypoints=websecure
        - traefik.http.routers.houseapp-api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.houseapp-api.service=houseapp_api
        - traefik.http.services.houseapp-api.loadbalancer.server.port=3333
    networks:
      - network_swarm_public

  web:
    image: ghcr.io/Fagner3g/houseapp-web:${TAG:-latest}
    env_file:
      - /opt/env/houseapp/web.env
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.http.routers.houseapp-web.rule=Host(`app.jarvis.dev.br`)
        - traefik.http.routers.houseapp-web.entrypoints=websecure
        - traefik.http.routers.houseapp-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.houseapp-web.service=houseapp_web
        - traefik.http.services.houseapp-web.loadbalancer.server.port=80
    networks:
      - network_swarm_public
