name: house-js-server

services:
  pg:
    image: bitnami/postgresql:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: houseapp