version: '3.8'

networks:
  network_swarm_public:
    external: true

services:
  api:
    image: ghcr.io/fagner3g/houseapp-api:${TAG:-develop}
    env_file:
      - /opt/stacks/houseapp/prod/api.env
    healthcheck:
      # Healthcheck roda dentro do próprio container; use 127.0.0.1 para evitar problemas de DNS
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:3333/health || wget -qO- http://127.0.0.1:3333/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.houseapp-api.rule=Host(`api.jarvis.dev.br`)
        - traefik.http.routers.houseapp-api.entrypoints=websecure
        - traefik.http.routers.houseapp-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.houseapp-api.loadbalancer.server.port=3333
    networks:
      - network_swarm_public

  web:
    image: ghcr.io/fagner3g/houseapp-web:${TAG:-develop}
    env_file:
      - /opt/stacks/houseapp/prod/web.env
    healthcheck:
      # Healthcheck roda dentro do próprio container; use 127.0.0.1 para evitar problemas de DNS
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1/health || wget -qO- http://127.0.0.1/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          cpus: "0.50"
          memory: 384M
        reservations:
          cpus: "0.10"
          memory: 96M
      labels:
        - traefik.enable=true
        - traefik.http.routers.houseapp-web.rule=Host(`app.jarvis.dev.br`)
        - traefik.http.routers.houseapp-web.entrypoints=websecure
        - traefik.http.routers.houseapp-web.tls.certresolver=letsencryptresolver
        - traefik.http.services.houseapp-web.loadbalancer.server.port=80
    networks:
      - network_swarm_public

