/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthValidateRouteImport } from './pages/_auth/validate'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthInviteRouteImport } from './pages/_auth/invite'
import { Route as AppNewOrgRouteImport } from './pages/_app/new-org'
import { Route as AppOrgIndexRouteImport } from './pages/_app/$org/index'
import { Route as AppOrgProfileRouteImport } from './pages/_app/$org/profile'
import { Route as AppOrgCreditCardsRouteImport } from './pages/_app/$org/credit-cards'
import { Route as AppOrgAccountsRouteImport } from './pages/_app/$org/accounts'
import { Route as AppOrgSettingsIndexRouteImport } from './pages/_app/$org/settings/index'
import { Route as AppOrgAccountsIndexRouteImport } from './pages/_app/$org/accounts/index'
import { Route as AppOrgSettingsMembersRouteImport } from './pages/_app/$org/settings/members'
import { Route as AppOrgSettingsGeneralRouteImport } from './pages/_app/$org/settings/general'
import { Route as AppOrgSettingsCategoriesRouteImport } from './pages/_app/$org/settings/categories'
import { Route as AppOrgSettingsAlertsRouteImport } from './pages/_app/$org/settings/alerts'
import { Route as AppOrgSettingsAccountsRouteImport } from './pages/_app/$org/settings/accounts'
import { Route as AppOrgAccountsIdRouteImport } from './pages/_app/$org/accounts/$id'
import { Route as AppOrguserUsersRouteImport } from './pages/_app/$org/(user)/users'
import { Route as AppOrgdashboardDashboardRouteImport } from './pages/_app/$org/(dashboard)/dashboard'
import { Route as AppOrgtransactionsTransactionsIndexRouteImport } from './pages/_app/$org/(transactions)/transactions/index'
import { Route as AppOrgtransactionsTransactionsOverdueRouteImport } from './pages/_app/$org/(transactions)/transactions/overdue'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthValidateRoute = AuthValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppNewOrgRoute = AppNewOrgRouteImport.update({
  id: '/new-org',
  path: '/new-org',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/$org/',
  path: '/$org/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgProfileRoute = AppOrgProfileRouteImport.update({
  id: '/$org/profile',
  path: '/$org/profile',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgCreditCardsRoute = AppOrgCreditCardsRouteImport.update({
  id: '/$org/credit-cards',
  path: '/$org/credit-cards',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgAccountsRoute = AppOrgAccountsRouteImport.update({
  id: '/$org/accounts',
  path: '/$org/accounts',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSettingsIndexRoute = AppOrgSettingsIndexRouteImport.update({
  id: '/$org/settings/',
  path: '/$org/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgAccountsIndexRoute = AppOrgAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgAccountsRoute,
} as any)
const AppOrgSettingsMembersRoute = AppOrgSettingsMembersRouteImport.update({
  id: '/$org/settings/members',
  path: '/$org/settings/members',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSettingsGeneralRoute = AppOrgSettingsGeneralRouteImport.update({
  id: '/$org/settings/general',
  path: '/$org/settings/general',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSettingsCategoriesRoute =
  AppOrgSettingsCategoriesRouteImport.update({
    id: '/$org/settings/categories',
    path: '/$org/settings/categories',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrgSettingsAlertsRoute = AppOrgSettingsAlertsRouteImport.update({
  id: '/$org/settings/alerts',
  path: '/$org/settings/alerts',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSettingsAccountsRoute = AppOrgSettingsAccountsRouteImport.update({
  id: '/$org/settings/accounts',
  path: '/$org/settings/accounts',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgAccountsIdRoute = AppOrgAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrgAccountsRoute,
} as any)
const AppOrguserUsersRoute = AppOrguserUsersRouteImport.update({
  id: '/$org/(user)/users',
  path: '/$org/users',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgdashboardDashboardRoute =
  AppOrgdashboardDashboardRouteImport.update({
    id: '/$org/(dashboard)/dashboard',
    path: '/$org/dashboard',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrgtransactionsTransactionsIndexRoute =
  AppOrgtransactionsTransactionsIndexRouteImport.update({
    id: '/$org/(transactions)/transactions/',
    path: '/$org/transactions/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrgtransactionsTransactionsOverdueRoute =
  AppOrgtransactionsTransactionsOverdueRouteImport.update({
    id: '/$org/(transactions)/transactions/overdue',
    path: '/$org/transactions/overdue',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-org': typeof AppNewOrgRoute
  '/invite': typeof AuthInviteRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/validate': typeof AuthValidateRoute
  '/$org/accounts': typeof AppOrgAccountsRouteWithChildren
  '/$org/credit-cards': typeof AppOrgCreditCardsRoute
  '/$org/profile': typeof AppOrgProfileRoute
  '/$org': typeof AppOrgIndexRoute
  '/$org/dashboard': typeof AppOrgdashboardDashboardRoute
  '/$org/users': typeof AppOrguserUsersRoute
  '/$org/accounts/$id': typeof AppOrgAccountsIdRoute
  '/$org/settings/accounts': typeof AppOrgSettingsAccountsRoute
  '/$org/settings/alerts': typeof AppOrgSettingsAlertsRoute
  '/$org/settings/categories': typeof AppOrgSettingsCategoriesRoute
  '/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/$org/accounts/': typeof AppOrgAccountsIndexRoute
  '/$org/settings': typeof AppOrgSettingsIndexRoute
  '/$org/transactions/overdue': typeof AppOrgtransactionsTransactionsOverdueRoute
  '/$org/transactions': typeof AppOrgtransactionsTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-org': typeof AppNewOrgRoute
  '/invite': typeof AuthInviteRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/validate': typeof AuthValidateRoute
  '/$org/credit-cards': typeof AppOrgCreditCardsRoute
  '/$org/profile': typeof AppOrgProfileRoute
  '/$org': typeof AppOrgIndexRoute
  '/$org/dashboard': typeof AppOrgdashboardDashboardRoute
  '/$org/users': typeof AppOrguserUsersRoute
  '/$org/accounts/$id': typeof AppOrgAccountsIdRoute
  '/$org/settings/accounts': typeof AppOrgSettingsAccountsRoute
  '/$org/settings/alerts': typeof AppOrgSettingsAlertsRoute
  '/$org/settings/categories': typeof AppOrgSettingsCategoriesRoute
  '/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/$org/accounts': typeof AppOrgAccountsIndexRoute
  '/$org/settings': typeof AppOrgSettingsIndexRoute
  '/$org/transactions/overdue': typeof AppOrgtransactionsTransactionsOverdueRoute
  '/$org/transactions': typeof AppOrgtransactionsTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/new-org': typeof AppNewOrgRoute
  '/_auth/invite': typeof AuthInviteRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/validate': typeof AuthValidateRoute
  '/_app/$org/accounts': typeof AppOrgAccountsRouteWithChildren
  '/_app/$org/credit-cards': typeof AppOrgCreditCardsRoute
  '/_app/$org/profile': typeof AppOrgProfileRoute
  '/_app/$org/': typeof AppOrgIndexRoute
  '/_app/$org/(dashboard)/dashboard': typeof AppOrgdashboardDashboardRoute
  '/_app/$org/(user)/users': typeof AppOrguserUsersRoute
  '/_app/$org/accounts/$id': typeof AppOrgAccountsIdRoute
  '/_app/$org/settings/accounts': typeof AppOrgSettingsAccountsRoute
  '/_app/$org/settings/alerts': typeof AppOrgSettingsAlertsRoute
  '/_app/$org/settings/categories': typeof AppOrgSettingsCategoriesRoute
  '/_app/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/_app/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/_app/$org/accounts/': typeof AppOrgAccountsIndexRoute
  '/_app/$org/settings/': typeof AppOrgSettingsIndexRoute
  '/_app/$org/(transactions)/transactions/overdue': typeof AppOrgtransactionsTransactionsOverdueRoute
  '/_app/$org/(transactions)/transactions/': typeof AppOrgtransactionsTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-org'
    | '/invite'
    | '/sign-in'
    | '/sign-up'
    | '/validate'
    | '/$org/accounts'
    | '/$org/credit-cards'
    | '/$org/profile'
    | '/$org'
    | '/$org/dashboard'
    | '/$org/users'
    | '/$org/accounts/$id'
    | '/$org/settings/accounts'
    | '/$org/settings/alerts'
    | '/$org/settings/categories'
    | '/$org/settings/general'
    | '/$org/settings/members'
    | '/$org/accounts/'
    | '/$org/settings'
    | '/$org/transactions/overdue'
    | '/$org/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-org'
    | '/invite'
    | '/sign-in'
    | '/sign-up'
    | '/validate'
    | '/$org/credit-cards'
    | '/$org/profile'
    | '/$org'
    | '/$org/dashboard'
    | '/$org/users'
    | '/$org/accounts/$id'
    | '/$org/settings/accounts'
    | '/$org/settings/alerts'
    | '/$org/settings/categories'
    | '/$org/settings/general'
    | '/$org/settings/members'
    | '/$org/accounts'
    | '/$org/settings'
    | '/$org/transactions/overdue'
    | '/$org/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/new-org'
    | '/_auth/invite'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/validate'
    | '/_app/$org/accounts'
    | '/_app/$org/credit-cards'
    | '/_app/$org/profile'
    | '/_app/$org/'
    | '/_app/$org/(dashboard)/dashboard'
    | '/_app/$org/(user)/users'
    | '/_app/$org/accounts/$id'
    | '/_app/$org/settings/accounts'
    | '/_app/$org/settings/alerts'
    | '/_app/$org/settings/categories'
    | '/_app/$org/settings/general'
    | '/_app/$org/settings/members'
    | '/_app/$org/accounts/'
    | '/_app/$org/settings/'
    | '/_app/$org/(transactions)/transactions/overdue'
    | '/_app/$org/(transactions)/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/validate': {
      id: '/_auth/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof AuthValidateRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/new-org': {
      id: '/_app/new-org'
      path: '/new-org'
      fullPath: '/new-org'
      preLoaderRoute: typeof AppNewOrgRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/': {
      id: '/_app/$org/'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/profile': {
      id: '/_app/$org/profile'
      path: '/$org/profile'
      fullPath: '/$org/profile'
      preLoaderRoute: typeof AppOrgProfileRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/credit-cards': {
      id: '/_app/$org/credit-cards'
      path: '/$org/credit-cards'
      fullPath: '/$org/credit-cards'
      preLoaderRoute: typeof AppOrgCreditCardsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/accounts': {
      id: '/_app/$org/accounts'
      path: '/$org/accounts'
      fullPath: '/$org/accounts'
      preLoaderRoute: typeof AppOrgAccountsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/settings/': {
      id: '/_app/$org/settings/'
      path: '/$org/settings'
      fullPath: '/$org/settings'
      preLoaderRoute: typeof AppOrgSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/accounts/': {
      id: '/_app/$org/accounts/'
      path: '/'
      fullPath: '/$org/accounts/'
      preLoaderRoute: typeof AppOrgAccountsIndexRouteImport
      parentRoute: typeof AppOrgAccountsRoute
    }
    '/_app/$org/settings/members': {
      id: '/_app/$org/settings/members'
      path: '/$org/settings/members'
      fullPath: '/$org/settings/members'
      preLoaderRoute: typeof AppOrgSettingsMembersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/settings/general': {
      id: '/_app/$org/settings/general'
      path: '/$org/settings/general'
      fullPath: '/$org/settings/general'
      preLoaderRoute: typeof AppOrgSettingsGeneralRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/settings/categories': {
      id: '/_app/$org/settings/categories'
      path: '/$org/settings/categories'
      fullPath: '/$org/settings/categories'
      preLoaderRoute: typeof AppOrgSettingsCategoriesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/settings/alerts': {
      id: '/_app/$org/settings/alerts'
      path: '/$org/settings/alerts'
      fullPath: '/$org/settings/alerts'
      preLoaderRoute: typeof AppOrgSettingsAlertsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/settings/accounts': {
      id: '/_app/$org/settings/accounts'
      path: '/$org/settings/accounts'
      fullPath: '/$org/settings/accounts'
      preLoaderRoute: typeof AppOrgSettingsAccountsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/accounts/$id': {
      id: '/_app/$org/accounts/$id'
      path: '/$id'
      fullPath: '/$org/accounts/$id'
      preLoaderRoute: typeof AppOrgAccountsIdRouteImport
      parentRoute: typeof AppOrgAccountsRoute
    }
    '/_app/$org/(user)/users': {
      id: '/_app/$org/(user)/users'
      path: '/$org/users'
      fullPath: '/$org/users'
      preLoaderRoute: typeof AppOrguserUsersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/(dashboard)/dashboard': {
      id: '/_app/$org/(dashboard)/dashboard'
      path: '/$org/dashboard'
      fullPath: '/$org/dashboard'
      preLoaderRoute: typeof AppOrgdashboardDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/(transactions)/transactions/': {
      id: '/_app/$org/(transactions)/transactions/'
      path: '/$org/transactions'
      fullPath: '/$org/transactions'
      preLoaderRoute: typeof AppOrgtransactionsTransactionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$org/(transactions)/transactions/overdue': {
      id: '/_app/$org/(transactions)/transactions/overdue'
      path: '/$org/transactions/overdue'
      fullPath: '/$org/transactions/overdue'
      preLoaderRoute: typeof AppOrgtransactionsTransactionsOverdueRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppOrgAccountsRouteChildren {
  AppOrgAccountsIdRoute: typeof AppOrgAccountsIdRoute
  AppOrgAccountsIndexRoute: typeof AppOrgAccountsIndexRoute
}

const AppOrgAccountsRouteChildren: AppOrgAccountsRouteChildren = {
  AppOrgAccountsIdRoute: AppOrgAccountsIdRoute,
  AppOrgAccountsIndexRoute: AppOrgAccountsIndexRoute,
}

const AppOrgAccountsRouteWithChildren = AppOrgAccountsRoute._addFileChildren(
  AppOrgAccountsRouteChildren,
)

interface AppLayoutRouteChildren {
  AppNewOrgRoute: typeof AppNewOrgRoute
  AppOrgAccountsRoute: typeof AppOrgAccountsRouteWithChildren
  AppOrgCreditCardsRoute: typeof AppOrgCreditCardsRoute
  AppOrgProfileRoute: typeof AppOrgProfileRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgdashboardDashboardRoute: typeof AppOrgdashboardDashboardRoute
  AppOrguserUsersRoute: typeof AppOrguserUsersRoute
  AppOrgSettingsAccountsRoute: typeof AppOrgSettingsAccountsRoute
  AppOrgSettingsAlertsRoute: typeof AppOrgSettingsAlertsRoute
  AppOrgSettingsCategoriesRoute: typeof AppOrgSettingsCategoriesRoute
  AppOrgSettingsGeneralRoute: typeof AppOrgSettingsGeneralRoute
  AppOrgSettingsMembersRoute: typeof AppOrgSettingsMembersRoute
  AppOrgSettingsIndexRoute: typeof AppOrgSettingsIndexRoute
  AppOrgtransactionsTransactionsOverdueRoute: typeof AppOrgtransactionsTransactionsOverdueRoute
  AppOrgtransactionsTransactionsIndexRoute: typeof AppOrgtransactionsTransactionsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppNewOrgRoute: AppNewOrgRoute,
  AppOrgAccountsRoute: AppOrgAccountsRouteWithChildren,
  AppOrgCreditCardsRoute: AppOrgCreditCardsRoute,
  AppOrgProfileRoute: AppOrgProfileRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgdashboardDashboardRoute: AppOrgdashboardDashboardRoute,
  AppOrguserUsersRoute: AppOrguserUsersRoute,
  AppOrgSettingsAccountsRoute: AppOrgSettingsAccountsRoute,
  AppOrgSettingsAlertsRoute: AppOrgSettingsAlertsRoute,
  AppOrgSettingsCategoriesRoute: AppOrgSettingsCategoriesRoute,
  AppOrgSettingsGeneralRoute: AppOrgSettingsGeneralRoute,
  AppOrgSettingsMembersRoute: AppOrgSettingsMembersRoute,
  AppOrgSettingsIndexRoute: AppOrgSettingsIndexRoute,
  AppOrgtransactionsTransactionsOverdueRoute:
    AppOrgtransactionsTransactionsOverdueRoute,
  AppOrgtransactionsTransactionsIndexRoute:
    AppOrgtransactionsTransactionsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthInviteRoute: typeof AuthInviteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthValidateRoute: typeof AuthValidateRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthInviteRoute: AuthInviteRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthValidateRoute: AuthValidateRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
