name: house-js-server

services:
  pg:
    image: bitnami/postgresql:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: houseapp
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: fagner.egomes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "80:80"
  evolution:
    image: atendai/evolution-api:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: 947C2156262E-423F-95F5-AD39E43F5A4B
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"